name: Daily Auto Commit

on:
  schedule:
    - cron: '30 14 * * *'  # 매일 14:30 UTC에 실행 (UTC+9 한국 시간 23:30)

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: 오늘 커밋 여부 확인
        run: |
          if git log --since='yesterday 14:30 UTC' --author="$GITHUB_ACTOR" --oneline | grep .; then
            echo "오늘 이미 커밋이 있습니다. 워크플로를 종료합니다."
            exit 0
          else
            echo "오늘 커밋이 없습니다. 자동 커밋을 진행합니다."
          fi

      - name: 파일 업데이트
        run: |
          DATE=$(TZ=Asia/Seoul date '+%Y-%m-%d')
          echo "오늘은 auto-commit bot이 잔디 심어요" > ${DATE}.txt

      - name: 변경 사항 커밋
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git add ${DATE}.txt
          git commit -m "자동 커밋: ${DATE}"

      - name: 변경 사항 푸시
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
